// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.513
package ui

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func QuickSearchDialogComponent() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"modal modal-lg\" id=\"quickSearchDialogModal\"><div class=\"modal-dialog modal-dialog-scrollable\" role=\"document\"><div class=\"modal-content\"><div class=\"modal-body px-3 py-3\"><div class=\"d-flex flex-row align-items-center gap-1\"><input id=\"quick_search_input\" type=\"search\" class=\"form-control\" placeholder=\"Search...\" aria-label=\"Search\"> <button type=\"button\" class=\"btn btn-outline-dark\" data-bs-dismiss=\"modal\" aria-label=\"Close\"><i class=\"bi bi-x-lg\"></i></button></div><div class=\"row mt-3\"><div class=\"list-group\" id=\"quick_search_results\"></div></div></div></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = quickSearchHandler().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}

func quickSearchHandler() templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_quickSearchHandler_710a`,
		Function: `function __templ_quickSearchHandler_710a(){function debounce(func, timeout = 500){
      let timer;
      return (...args) => {
        clearTimeout(timer);
        timer = setTimeout(() => { func.apply(this, args); }, timeout);
      };
    }


    // Function to make the HTTP request
    async function makeHttpRequest(inputValue) {
      const apiUrl = '/api/v1/product/search?name=' + encodeURIComponent(inputValue);

      const response = await fetch(apiUrl)
      const jsonResponse = await response.json()
      return jsonResponse.items;
    }

    const inputElem = document.getElementById("quick_search_input")
    inputElem.addEventListener("input", debounce(async () => {
      if (inputElem.value != "") {
        const items = await makeHttpRequest(inputElem.value)
        const resultsContainer = document.getElementById("quick_search_results")
        resultsContainer.innerText = ""
        items.forEach(item => {
          addSearchResult(item.product_id, item.image_url, item.name, item.store_name, item.price / 100, item.discount_percent > 0); 
        })
      }
    }))

    function addSearchResult(productId, imageUrl, productName, storeName, price, isDiscount) {
      const parent = document.getElementById("quick_search_results")  
      const className = isDiscount ? "alert-success" : "alert-danger";
      
      const a = document.createElement("a")
      a.href = ` + "`" + `/${productId}` + "`" + `
      a.className = "list-group-item list-group-item-action"
    
      a.innerHTML = ` + "`" + `
      <div class='row'>
        <div class='col-md-2'>
          <img class='d-block' src='${imageUrl}' width='80px'/>
        </div>
        <div class='col-md-8'>
          <strong class="list-group-item-heading">${productName}</strong>
          <p class="list-group-item-text">${storeName}</p>
        </div>
        <div class='col-md-2'>
          <span class="badge ${className}">${price} €</span>
        </div>
        </div>
      ` + "`" + `
      parent.appendChild(a)
    }}`,
		Call:       templ.SafeScript(`__templ_quickSearchHandler_710a`),
		CallInline: templ.SafeScriptInline(`__templ_quickSearchHandler_710a`),
	}
}
