BEGIN;

CREATE TABLE IF NOT EXISTS PRODUCT_PRICE
(
    PRODUCT_ID BIGINT PRIMARY KEY,
    DATE_TIME TIMESTAMP NOT NULL DEFAULT(NOW()),
    PRICE NUMERIC(12, 4) NOT NULL,

    CONSTRAINT FK_PRODUCT_ID FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (PRODUCT_ID)
);

COMMIT;