BEGIN;
CREATE TABLE IF NOT EXISTS PRODUCT
(
    PRODUCT_ID BIGSERIAL PRIMARY KEY,
    STORE_ID BIGINT NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    BRAND VARCHAR(255),
    PRICE NUMERIC(12, 4) NOT NULL,
    AVAILABLE BOOL NOT NULL DEFAULT TRUE,
    IMAGE_URL VARCHAR(255),
    PRODUCT_URL VARCHAR(255) NOT NULL,
    
    CONSTRAINT UK_PRODUCT_URL UNIQUE (PRODUCT_URL),
    CONSTRAINT FK_PRODUCT_STORE_ID FOREIGN KEY (STORE_ID) REFERENCES STORE (STORE_ID)
);
COMMIT;