BEGIN;

CREATE TABLE IF NOT EXISTS PRODUCT_PRICE
(
    PRODUCT_ID BIGINT,
    DATE_TIME TIMESTAMP NOT NULL DEFAULT(NOW()),
    PRICE NUMERIC(12, 4) NOT NULL,

    CONSTRAINT FK_PRODUCT_ID FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (PRODUCT_ID),
    PRIMARY KEY(PRODUCT_ID, DATE_TIME)
);

COMMIT;