database:
  dsn: "host=localhost port=5432 user=postgres password=price dbname=postgres sslmode=disable timezone=UTC connect_timeout=5"
  attempts: 5
  migrate: true
messagequeue:
  url: amqp://user:price@localhost:5672/
  manualAck: false
  threadCount: 5
