ALTER TABLE PRODUCT ADD COLUMN SEARCH_VECTOR TSVECTOR;
UPDATE PRODUCT SET SEARCH_VECTOR = to_tsvector('english', brand || ' ' || name);
CREATE INDEX PRODUCT_SEARCH_VECTOR_IDX ON PRODUCT USING gin(search_vector);