BEGIN;

CREATE TABLE IF NOT EXISTS PRODUCT_EAN
(
    PRODUCT_ID BIGINT NOT NULL,
    EAN BIGINT NOT NULL,

    CONSTRAINT FK_PRODUCT_ID FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (PRODUCT_ID),
    PRIMARY KEY(PRODUCT_ID, EAN)
);

COMMIT;