BEGIN;

CREATE TABLE IF NOT EXISTS PRODUCT_STATS
(
    PRODUCT_ID BIGINT,
    PRICE INTEGER NOT NULL,
    DIFFERENCE NUMERIC(10, 2) NOT NULL,
    DISCOUNT_PERCENT NUMERIC(10, 2) NOT NULL,
    AVERAGE NUMERIC(10,2) NOT NULL,
    MAXIMUM NUMERIC(10,2) NOT NULL,
    MINIMUM NUMERIC(10,2) NOT NULL,
    ENTRIES INTEGER NOT NULL,

    CONSTRAINT FK_PRODUCT_ID FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (PRODUCT_ID)
);

COMMIT;